# Generated by Django 3.1.4 on 2021-01-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theseven', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=9, null=True),
        ),
    ]
