# Generated by Django 3.1.4 on 2021-01-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theseven', '0002_auto_20210103_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
